version: '3.8'

services:
  # Development service
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_FEED_SERVICE_URL=http://localhost:8000
      - NEXT_PUBLIC_CMS_SERVICE_URL=http://localhost:8002
    networks:
      - startup-network

  # Production service
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_FEED_SERVICE_URL=https://startup-news-feed.onrender.com
      - NEXT_PUBLIC_CMS_SERVICE_URL=https://startup-news-cms.onrender.com
    networks:
      - startup-network
    restart: unless-stopped

networks:
  startup-network:
    driver: bridge
